# Generated by Django 4.2.2 on 2023-07-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whey',
            old_name='description',
            new_name='brand_name',
        ),
    ]
